# Generated by Django 5.0.2 on 2024-02-24 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume_parser', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
