# Generated by Django 5.0.2 on 2024-02-25 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume_parser', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobposting',
            name='posted_by',
        ),
    ]
