# Generated by Django 5.0.2 on 2024-02-25 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_parser', '0003_remove_jobposting_posted_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
