# Generated by Django 5.0.2 on 2024-02-25 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume_parser', '0004_resume_file_alter_resume_email_alter_resume_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='user',
        ),
    ]
