# Generated by Django 5.0.2 on 2024-02-26 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_parser', '0006_remove_resume_education_remove_resume_experience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
